/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/data/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current met.sqlite artifact version */
        get: operations["getDataVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/museums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Museums contained in the current artifact
         * @description The multi-museum manifest: registry identity, sites (buildings with entrances + floor order), data fidelity/capabilities, licensing attribution, per-museum freshness. Read from the artifact's meta — the client sees identical facts offline from its downloaded copy.
         */
        get: operations["getMuseums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/met.sqlite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the met.sqlite artifact
         * @description Versioned binary download. ETag equals dataVersion; clients send If-None-Match and re-download only on version change.
         */
        get: operations["getDatabase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/img/{objectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cached proxy for an object's Met CDN image
         * @description Disk-cached pass-through of objects.imageUrl from met.sqlite. Exists because images.metmuseum.org sends no CORS/CORP headers, which the web client's COEP (require-corp, needed for SharedArrayBuffer / expo-sqlite) would block. Only objectIDs present in the catalog with a non-empty imageUrl are served, so this is not an open proxy. The objectID→image mapping is stable, so responses are immutable; clients cache-bust with ?v={dataVersion} when the catalog updates.
         */
        get: operations["getObjectImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LLM query interpretation, executed and ranked server-side
         * @description One client round trip. The server rewrites the natural-language query to an FTS query (escalating to a bounded agentic loop when the rewrite yields <3 rows or only low-signal bm25 scores), executes it against its met.sqlite, and returns final ranked results.
         */
        post: operations["interpretSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locate/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Locate the user from a photo
         * @description Two concurrent server-side paths: wall-label OCR (deterministic met.sqlite match when legible) and image-embedding retrieval against the on-view index (top-3 candidates). Clients downscale before upload; decoded image must be ≤4 MB.
         */
        post: operations["locatePhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency status */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                /** @description Seconds until retry is sensible (present on 429/503) */
                retryAfter?: number;
            };
        };
        DataVersion: {
            dataVersion: string;
            /** @description Size of met.sqlite in bytes (0 until first build) */
            sqliteBytes: number;
            /** Format: date-time */
            builtAt: string;
        };
        SiteMeta: {
            /** @description Globally unique site id ("fifthAve", "louvre:main", …) */
            siteId: string;
            name: string;
            entrance: {
                lat: number;
                lon: number;
                floor?: string;
            };
            /** @description Floor labels in display order (bottom → top) */
            floorOrder: string[];
        };
        MuseumEntry: {
            id: string;
            name: string;
            shortName: string;
            city: string;
            country: string;
            sites: components["schemas"]["SiteMeta"][];
            /** @enum {string} */
            fidelity: "routed" | "room-labels" | "museum-only";
            license: {
                text: string;
                /** @description Default image-derivative license; "" = none allowed */
                images: string;
                attribution: string;
                termsUrl: string;
                /** @description Non-commercial-use TTL in days for sources whose terms cap how long fetched content may be cached/served (e.g. V&A: 4 weeks). When set, the license-TTL mechanism hides this museum's rows once the shipped artifact is older than ttlDays - 1 (see ARCHITECTURE.md "Provenance & the license-TTL mechanism"). */
                ttlDays?: number;
            };
            /** @description Object deep-link template; "{sourceId}" replaced per record */
            objectUrlTemplate?: string;
            capabilities: {
                hasGeometry: boolean;
                hasGraph: boolean;
                /** @enum {string} */
                granularity: "room" | "gallery-label" | "museum";
                languages: string[];
            };
            counts?: {
                objects?: number;
            };
            /** @description When this museum's records were last confirmed from source */
            fetchedAt?: string | null;
        };
        MuseumManifest: {
            dataVersion: string;
            /** Format: date-time */
            builtAt: string;
            museums: components["schemas"]["MuseumEntry"][];
        };
        Health: {
            ok: boolean;
            dataVersion: string;
            /** @enum {string} */
            llm: "up" | "degraded";
        };
        InterpretRequest: {
            query: string;
            /** @default 10 */
            maxResults: number;
            /** @description Optional museum registry id ("met", "aic", …) to scope interpretation and execution to one museum (schema v2 multi-museum artifacts; the client's ScopeChips "AT {museum}" selection). Omitted = search across every museum in the artifact. */
            museum?: string;
        };
        InterpretedQuery: {
            /** @description The FTS5 query the server executed */
            ftsQuery: string;
            filters: {
                artist?: string;
                classification?: string;
                material?: string;
                culture_or_period?: string;
            };
        };
        SearchResult: {
            objectID: number;
            title: string;
            artist: string;
            galleryNumber: string;
            floor: string;
            /** @enum {string} */
            site: "fifthAve" | "cloisters";
            score: number;
        };
        InterpretResponse: {
            results: components["schemas"]["SearchResult"][];
            /** @enum {string} */
            method: "rewrite" | "agentic";
            interpretedQuery: components["schemas"]["InterpretedQuery"];
            /** @description One-line explanation (agentic path only) */
            why?: string;
        };
        LocatePhotoRequest: {
            /** @description JPEG/PNG bytes, base64-encoded; decoded size ≤4 MB */
            imageBase64: string;
        };
        LabelMatch: {
            objectID: number;
            gallery: string;
            floor: string;
            accession: string;
            confidence: number;
        };
        LocateCandidate: {
            objectID: number;
            title: string;
            artist: string;
            gallery: string;
            floor: string;
            similarity: number;
        };
        LocatePhotoResponse: {
            /** @description Deterministic wall-label match; null if no label legible */
            label?: components["schemas"]["LabelMatch"] | null;
            candidates: components["schemas"]["LocateCandidate"][];
        };
    };
    responses: {
        /** @description Standard error envelope. Codes include invalid_request (400), not_found (404), payload_too_large (413), not_implemented (501), budget_exhausted (503, daily LLM cap tripped), internal (500). */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Per-IP rate limit exceeded; retry after the indicated delay. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Current met.sqlite dataVersion. Sent on every API response so a stale client knows to re-pull /api/v1/data/met.sqlite. */
        XDataVersion: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDataVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact version metadata */
            200: {
                headers: {
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMuseums: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Museum manifest */
            200: {
                headers: {
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuseumManifest"];
                };
            };
            /** @description Artifact not yet available (data_unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDatabase: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The SQLite database file */
            200: {
                headers: {
                    /** @description Equals the current dataVersion */
                    ETag?: string;
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Client copy is current (If-None-Match matched) */
            304: {
                headers: {
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getObjectImage: {
        parameters: {
            query?: {
                /** @description Cache-buster; clients pass the current dataVersion. */
                v?: string;
            };
            header?: never;
            path: {
                objectID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes (Met CDN pass-through; in practice JPEG) */
            200: {
                headers: {
                    /** @description public, max-age=31536000, immutable */
                    "Cache-Control"?: string;
                    /** @description Always "*" (images are public CC0) */
                    "Access-Control-Allow-Origin"?: string;
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description Unknown objectID, or the object has no image */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description Upstream Met CDN fetch failed or timed out (never cached) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    interpretSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretRequest"];
            };
        };
        responses: {
            /** @description Final ranked results */
            200: {
                headers: {
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    locatePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocatePhotoRequest"];
            };
        };
        responses: {
            /** @description Label match (if a label was legible) and retrieval candidates */
            200: {
                headers: {
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocatePhotoResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Error"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server status */
            200: {
                headers: {
                    "x-data-version": components["headers"]["XDataVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
